import { frames as manifest } from '../constant/frames';
import type { FrameEntry } from '../constant/frames';

export type ImageProps = FrameEntry;

export async function getBlobImages(): Promise<ImageProps[]> {
  // manifest is pre-generated by scripts/upload-frames.ts
  // no runtime blob API call needed — URLs are public
  return manifest;
}
