import { put } from '@vercel/blob';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';

const FRAMES_DIR = join(import.meta.dirname, '..', 'public', 'frames');
const MANIFEST_PATH = join(import.meta.dirname, '..', 'src', 'constant', 'frames.ts');

const GRID_WIDTH = 660; // 2x for retina, displayed at 330px

interface FrameEntry {
  pathname: string;
  url: string; // original, full quality
  thumbUrl: string; // 96×72 (2x of 48×36) for command bar
  gridUrl: string; // 660w, auto height (2x of 330w) for frames page
  gridWidth: number;
  gridHeight: number;
  width: number;
  height: number;
  blurDataUrl: string; // 10px hash placeholder
}

async function main() {
  const files = readdirSync(FRAMES_DIR).filter((f) =>
    /\.(jpg|jpeg|png|webp|avif)$/i.test(f),
  );

  if (files.length === 0) {
    console.log('No images found in public/frames/');
    return;
  }

  console.log(`Uploading ${files.length} frame${files.length > 1 ? 's' : ''}...`);

  const frames: FrameEntry[] = [];

  for (const file of files.toSorted()) {
    const filePath = join(FRAMES_DIR, file);
    const buf = readFileSync(filePath);
    const name = file.replace(/\.[^.]+$/, '');

    process.stdout.write(`  ${file} (${(buf.length / 1024 / 1024).toFixed(1)}MB)... `);

    // 1. Upload original (full quality, untouched)
    const { url, pathname } = await put(file, buf, {
      access: 'public',
      addRandomSuffix: false,
      allowOverwrite: true,
    });

    // 2. Generate and upload 96×72 thumbnail (2x for command bar, displayed at 48×36)
    const thumbBuf = await sharp(buf)
      .resize(192, 192, { fit: 'cover' })
      .jpeg({ quality: 80 })
      .toBuffer();
    const { url: thumbUrl } = await put(`${name}-thumb.jpg`, thumbBuf, {
      access: 'public',
      addRandomSuffix: false,
      allowOverwrite: true,
    });

    // 3. Generate grid variant — 660px wide (2x of 330px), auto height
    const gridBuf = await sharp(buf)
      .resize(GRID_WIDTH, undefined, { fit: 'inside', withoutEnlargement: true })
      .jpeg({ quality: 85 })
      .toBuffer();
    const gridMeta = await sharp(gridBuf).metadata();
    const { url: gridUrl } = await put(`${name}-grid.jpg`, gridBuf, {
      access: 'public',
      addRandomSuffix: false,
      allowOverwrite: true,
    });

    // 4. Generate blur hash (10px placeholder)
    const meta = await sharp(buf).metadata();
    const placeholder = await sharp(buf)
      .resize(10)
      .jpeg({ quality: 70 })
      .toBuffer();

    frames.push({
      pathname,
      url,
      thumbUrl,
      gridUrl,
      gridWidth: gridMeta.width ?? GRID_WIDTH,
      gridHeight: gridMeta.height ?? 0,
      width: meta.width ?? 0,
      height: meta.height ?? 0,
      blurDataUrl: `data:image/jpeg;base64,${placeholder.toString('base64')}`,
    });

    console.log(`done (grid: ${gridMeta.width}×${gridMeta.height})`);
  }

  // Write manifest
  const manifest = `// Auto-generated by scripts/upload-frames.ts — do not edit by hand
// Run: bun run scripts/upload-frames.ts

export interface FrameEntry {
  pathname: string;
  url: string;           // original, full quality
  thumbUrl: string;      // 96×72 (2x of 48×36) for command bar
  gridUrl: string;       // 660w auto-height (2x of 330w) for frames page
  gridWidth: number;     // actual width of grid variant
  gridHeight: number;    // actual height of grid variant
  width: number;         // original width
  height: number;        // original height
  blurDataUrl: string;   // 10px hash placeholder
}

export const frames: FrameEntry[] = ${JSON.stringify(frames, null, 2)};
`;

  writeFileSync(MANIFEST_PATH, manifest);
  console.log(`\nWrote ${frames.length} entries to src/constant/frames.ts`);
}

main().catch((err) => {
  console.error('Upload failed:', err);
  process.exit(1);
});
