import { put } from '@vercel/blob';
import sharp from 'sharp';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';

const FRAMES_DIR = join(import.meta.dirname, '..', 'public', 'frames');
const MANIFEST_PATH = join(import.meta.dirname, '..', 'src', 'constant', 'frames.ts');

interface FrameEntry {
  pathname: string;
  url: string;
  width: number;
  height: number;
  blurDataUrl: string;
}

async function main() {
  const files = readdirSync(FRAMES_DIR).filter((f) =>
    /\.(jpg|jpeg|png|webp|avif)$/i.test(f),
  );

  if (files.length === 0) {
    console.log('No images found in public/frames/');
    return;
  }

  console.log(`Uploading ${files.length} frame${files.length > 1 ? 's' : ''}...`);

  const frames: FrameEntry[] = [];

  for (const file of files.sort()) {
    const filePath = join(FRAMES_DIR, file);
    const buf = readFileSync(filePath);

    process.stdout.write(`  ${file} (${(buf.length / 1024 / 1024).toFixed(1)}MB)... `);

    // Upload to Vercel Blob
    const { url, pathname } = await put(file, buf, {
      access: 'public',
      addRandomSuffix: false,
    });

    // Generate metadata with sharp
    const meta = await sharp(buf).metadata();
    const placeholder = await sharp(buf)
      .resize(10)
      .jpeg({ quality: 70 })
      .toBuffer();

    frames.push({
      pathname,
      url,
      width: meta.width ?? 0,
      height: meta.height ?? 0,
      blurDataUrl: `data:image/jpeg;base64,${placeholder.toString('base64')}`,
    });

    console.log('done');
  }

  // Write manifest
  const manifest = `// Auto-generated by scripts/upload-frames.ts — do not edit by hand
// Run: bun run scripts/upload-frames.ts

export interface FrameEntry {
  pathname: string;
  url: string;
  width: number;
  height: number;
  blurDataUrl: string;
}

export const frames: FrameEntry[] = ${JSON.stringify(frames, null, 2)};
`;

  writeFileSync(MANIFEST_PATH, manifest);
  console.log(`\nWrote ${frames.length} entries to src/constant/frames.ts`);
}

main().catch((err) => {
  console.error('Upload failed:', err);
  process.exit(1);
});
